"""Generates CONTEXT.md, CLAUDE.md, AGENTS.md inside the watched folder."""
from __future__ import annotations

from datetime import datetime
from pathlib import Path

from .db import Store
from .git_info import get_git_info

AGENT_FILES = ("CLAUDE.md", "AGENTS.md")
CONTEXT_FILE = "CONTEXT.md"

# Markers so we can tell "our" content apart from the user's hand-written
# instructions and safely merge rather than overwrite.
_BEGIN = "<!-- BEGIN CodeGraph auto-generated -->"
_END = "<!-- END CodeGraph auto-generated -->"
_LEGACY_MARKER = "<!-- AUTO-GENERATED by CodeGraph"  # older format

_HEADER = """# Project Context — auto-generated
_Last updated: {ts}_

Agents (Claude Code, Antigravity, Cursor, Codex, etc.): **read this file first**.
It reflects the live state of the project, refreshed on every file save.
"""

_AGENT_PREAMBLE = """# Agent instructions

The full live project context is below (mirrored from `CONTEXT.md`). Treat it as
authoritative for the current shape of the codebase. It is regenerated on every
file change by the CodeGraph watcher.

---

"""


def _wrap(body: str) -> str:
    return f"{_BEGIN}\n{body}\n{_END}\n"


def _merge_into(existing: str, block: str) -> str:
    """Preserve the user's hand-written content; replace only our auto block."""
    if _BEGIN in existing and _END in existing:
        pre, _, rest = existing.partition(_BEGIN)
        _, _, post = rest.partition(_END)
        return f"{pre.rstrip()}\n\n{block}\n{post.lstrip()}".strip() + "\n"
    if _LEGACY_MARKER in existing:
        # Entire file was ours under the old format: safe to replace wholesale.
        return block
    if not existing.strip():
        return block
    # User has their own content and we've never touched this file. Append ours
    # below a visible separator, leaving their content intact and on top.
    return f"{existing.rstrip()}\n\n---\n\n{block}"


def _write_or_merge(path: Path, block: str):
    try:
        existing = path.read_text(encoding="utf-8") if path.exists() else ""
    except Exception:
        existing = ""
    merged = _merge_into(existing, block)
    if merged != existing:
        path.write_text(merged, encoding="utf-8")


def write_all(folder: Path, store: Store):
    body = _build_context(folder, store)
    ctx_block = _wrap(body)
    # CONTEXT.md is "ours" — full ownership. But still merge so users who
    # sneak notes above the marker keep them.
    _write_or_merge(folder / CONTEXT_FILE, ctx_block)
    agent_block = _wrap(_AGENT_PREAMBLE + body)
    for fname in AGENT_FILES:
        _write_or_merge(folder / fname, agent_block)


def _git_section(folder: Path) -> list[str]:
    info = get_git_info(folder)
    if not info:
        return []
    out = ["## Git\n", f"- **Branch:** `{info['branch']}`"]
    if info["last_commit"]:
        out.append(f"- **Last commit:** {info['last_commit']}")
    if info["ahead"] or info["behind"]:
        ab = []
        if info["ahead"] and info["ahead"] != "0":
            ab.append(f"{info['ahead']} ahead")
        if info["behind"] and info["behind"] != "0":
            ab.append(f"{info['behind']} behind")
        if ab:
            out.append(f"- **Upstream:** {', '.join(ab)}")
    dirty = info["dirty"]
    if dirty:
        out.append(f"- **Uncommitted ({len(dirty)}):**")
        for code, path in dirty[:20]:
            out.append(f"  - `{code}` {path}")
        if len(dirty) > 20:
            out.append(f"  - …and {len(dirty) - 20} more")
    else:
        out.append("- **Working tree:** clean")
    out.append("")
    return out


def _build_context(folder: Path, store: Store) -> str:
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    out = [_HEADER.format(ts=ts)]

    out.extend(_git_section(folder))

    stats = store.stats()
    by_kind = stats["by_kind"]
    out.append("## Stats\n")
    out.append(f"- Total graph nodes: **{stats['total']}**")
    for k in ("file", "class", "function", "import"):
        if k in by_kind:
            label = {"class": "Classes", "file": "Files", "function": "Functions", "import": "Imports"}[k]
            out.append(f"- {label}: {by_kind[k]}")
    if stats["file_exts"]:
        ext_str = ", ".join(f"`{e or '?'}`×{c}" for e, c in sorted(stats["file_exts"].items()))
        out.append(f"- File types: {ext_str}")
    out.append("")

    changes = store.recent_changes(limit=25)
    out.append("## Recent changes (last 25)\n")
    if not changes:
        out.append("_No changes yet._")
    else:
        for c in changes:
            out.append(f"- `{c['ts']}`  **{c['kind']}**  `{c['path']}`")
    out.append("")

    nodes = store.all_nodes()
    edges = store.all_edges()
    files = sorted([n for n in nodes if n["kind"] == "file"], key=lambda n: n["path"])
    by_file: dict[str, dict] = {f["path"]: {"funcs": [], "classes": [], "imports": []} for f in files}
    sym_by_id = {n["id"]: n for n in nodes}
    for e in edges:
        if e["kind"] == "contains":
            src = sym_by_id.get(e["src"])
            dst = sym_by_id.get(e["dst"])
            if not src or not dst or src["kind"] != "file":
                continue
            bucket = by_file.setdefault(src["path"], {"funcs": [], "classes": [], "imports": []})
            if dst["kind"] == "function":
                bucket["funcs"].append(dst["name"])
            elif dst["kind"] == "class":
                bucket["classes"].append(dst["name"])
        elif e["kind"] == "imports":
            src = sym_by_id.get(e["src"])
            dst = sym_by_id.get(e["dst"])
            if not src or not dst:
                continue
            bucket = by_file.setdefault(src["path"], {"funcs": [], "classes": [], "imports": []})
            bucket["imports"].append(dst["name"])

    out.append("## Files\n")
    if not files:
        out.append("_No parsed files yet._")
    for f in files:
        b = by_file.get(f["path"], {"funcs": [], "classes": [], "imports": []})
        out.append(f"### `{f['path']}`")
        if b["classes"]:
            out.append(f"- **Classes:** {', '.join(sorted(set(b['classes'])))}")
        if b["funcs"]:
            out.append(f"- **Functions:** {', '.join(sorted(set(b['funcs'])))}")
        if b["imports"]:
            out.append(f"- **Imports:** {', '.join(sorted(set(b['imports'])))}")
        out.append("")

    return "\n".join(out)
